
/**
 * Author:  leandro.brito
 * Created: Sep 14, 2016
    SELECTS PARA MELHOR DESEPENHO 15/09/2016
 */
DELETE FROM PHE_CALENDARIO_ESCOLA;
DELETE FROM PHE_DIAS_NAO_LETIVOS;
DELETE FROM PHE_CALENDARIO_DOCENTE;
