/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Ets.areias
 * Created: 26/08/2016
 */


/* INSERINDO DADOS NO SQL SERVER *///
INSERT dbo.NOME_DO_BANCO (CAMPOS) VALUES (VALORES_DOS_CAMPOS);

/* EXEMPLO */
INSERT dbo.PHE_CALENDARIO_ESCOLA (DESCRICAO,DATADIA,DIASEMANA,AULA) VALUES ('TESTE','2017-02-02','2','AULA01');

/* CONSULTADAS NO SQL SERVER */
SELECT * FROM NOME_TABELA;

/*EXEMPLO */
SELECT * FROM PHE.CALENDARIO_ESCOLA;

/*UPDATE NO SQL SERVER */
UPDATE NOME_DO_BANCO SET CAMPO = VALOR_DESEJADO;

/* EXEMPLO */
UPDATE dbo.PHE_CALENDARIO_ESCOLA SET STATUS = 'I', DESCRICAO = 'EXEMPLO';

/* DELETE NO SQL SERVER*/
DELETE FROM TABELA_DESEJADA;

/*EXEMPLO */
DELETE FROM PHE_ESCOLAR;

/* CONSULTA PRONTA */

SELECT * FROM PHE_CALENDARIO_ESCOLA;
SELECT * FROM PHE_SHORARIO;
SELECT * FROM PHE_SHORARIO;

/*CONSULTA QUE UNE DDUAS TABELAS COM O INNER JOIN PARA PODER PEGAR INFORMAÇÕES*/
SELECT H.CODHOR, H.CODTURNO, H.DIASEMANA,H.HORAINICIAL,H.HORAFINAL,H.AULA,T.CODFILIAL,T.CODTURNO
FROM dbo.PHE_SHORARIO H 
INNER JOIN dbo.PHE_STURNO T 
ON H.CODTURNO = T.CODTURNO
WHERE (T.CODFILIAL = 1)
AND (H.DIASEMANA = 2);

/* SELECT QUE SELECIONA O ULTIMO REGISTRO ADICIONADO*/
SELECT TOP 1 DATADIA
FROM PHE_CALENDARIO_ESCOLA
WHERE CODFILIAL = 1 AND CODTURNO = 1
            ORDER BY DATADIA DESC


/*SELECIONA O REGISTRO DATA, SEM QUE HAJA REPETIÇOES DE VALORES*/
SELECT DISTINCT DATADIA FROM PHE_CALENDARIO_DOCENTE WHERE FNL = 1 AND CODIGODOCENTE = 83

DELETE FROM PHE_AGENDA_ESCOLA;
DELETE FROM PHE_HORARIO
DELETE FROM CODTURNO
